[project]
name = "sloop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zhandgw", email = "zhangdw.cs@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "openai>=2.14.0",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "tqdm>=4.67.1",
    "typer>=0.20.0",
]

[project.scripts]
sloop = "sloop.cli.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
