blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: [https://github.com/zhang-105/Sloop/discussions](https://github.com/zhang-105/Sloop/discussions)
    about: Please ask and answer questions here.
