# 默认的 Agent 配置
# 当用户未指定配置文件时，将使用此配置

generation:
  user_agent: "SimpleUserAgent"
  assistant_agent: "SimpleAssistantAgent"
  service_agent: "SimpleServiceAgent"
  planner: "SimplePlanner"
  user_profile_agent: "SimpleUserProfileAgent"
  api_sampler: "RandomAPISampler"

# probing:
#   capability_prober: "SimpleCapabilityProber"

# optimization:
#   data_optimizer: "SimpleDataOptimizer"
